//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class MJointPositions : Message
    {
        public const string RosMessageName = "robotics_demo/JointPositions";

        public float shoulder;
        public float upper_arm;
        public float forearm;
        public float wrist_1;
        public float wrist_2;
        public float wrist_3;
        public float gripper;
        public double time;

        public MJointPositions()
        {
            this.shoulder = 0.0f;
            this.upper_arm = 0.0f;
            this.forearm = 0.0f;
            this.wrist_1 = 0.0f;
            this.wrist_2 = 0.0f;
            this.wrist_3 = 0.0f;
            this.gripper = 0.0f;
            this.time = 0.0;
        }

        public MJointPositions(float shoulder, float upper_arm, float forearm, float wrist_1, float wrist_2, float wrist_3, float gripper, double time)
        {
            this.shoulder = shoulder;
            this.upper_arm = upper_arm;
            this.forearm = forearm;
            this.wrist_1 = wrist_1;
            this.wrist_2 = wrist_2;
            this.wrist_3 = wrist_3;
            this.gripper = gripper;
            this.time = time;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.shoulder));
            listOfSerializations.Add(BitConverter.GetBytes(this.upper_arm));
            listOfSerializations.Add(BitConverter.GetBytes(this.forearm));
            listOfSerializations.Add(BitConverter.GetBytes(this.wrist_1));
            listOfSerializations.Add(BitConverter.GetBytes(this.wrist_2));
            listOfSerializations.Add(BitConverter.GetBytes(this.wrist_3));
            listOfSerializations.Add(BitConverter.GetBytes(this.gripper));
            listOfSerializations.Add(BitConverter.GetBytes(this.time));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.shoulder = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.upper_arm = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.forearm = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.wrist_1 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.wrist_2 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.wrist_3 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.gripper = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.time = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MJointPositions: " +
            "\nshoulder: " + shoulder.ToString() +
            "\nupper_arm: " + upper_arm.ToString() +
            "\nforearm: " + forearm.ToString() +
            "\nwrist_1: " + wrist_1.ToString() +
            "\nwrist_2: " + wrist_2.ToString() +
            "\nwrist_3: " + wrist_3.ToString() +
            "\ngripper: " + gripper.ToString() +
            "\ntime: " + time.ToString();
        }
    }
}
