//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class MQuaternionProprioState : Message
    {
        public const string RosMessageName = "robotics_demo/QuaternionProprioState";

        public float pos_x;
        public float pos_y;
        public float pos_z;
        public float q1;
        public float q2;
        public float q3;
        public float q4;
        public float gripper;

        public MQuaternionProprioState()
        {
            this.pos_x = 0.0f;
            this.pos_y = 0.0f;
            this.pos_z = 0.0f;
            this.q1 = 0.0f;
            this.q2 = 0.0f;
            this.q3 = 0.0f;
            this.q4 = 0.0f;
            this.gripper = 0.0f;
        }

        public MQuaternionProprioState(float pos_x, float pos_y, float pos_z, float q1, float q2, float q3, float q4, float gripper)
        {
            this.pos_x = pos_x;
            this.pos_y = pos_y;
            this.pos_z = pos_z;
            this.q1 = q1;
            this.q2 = q2;
            this.q3 = q3;
            this.q4 = q4;
            this.gripper = gripper;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.pos_x));
            listOfSerializations.Add(BitConverter.GetBytes(this.pos_y));
            listOfSerializations.Add(BitConverter.GetBytes(this.pos_z));
            listOfSerializations.Add(BitConverter.GetBytes(this.q1));
            listOfSerializations.Add(BitConverter.GetBytes(this.q2));
            listOfSerializations.Add(BitConverter.GetBytes(this.q3));
            listOfSerializations.Add(BitConverter.GetBytes(this.q4));
            listOfSerializations.Add(BitConverter.GetBytes(this.gripper));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.pos_x = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.pos_y = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.pos_z = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.q1 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.q2 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.q3 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.q4 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.gripper = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MQuaternionProprioState: " +
            "\npos_x: " + pos_x.ToString() +
            "\npos_y: " + pos_y.ToString() +
            "\npos_z: " + pos_z.ToString() +
            "\nq1: " + q1.ToString() +
            "\nq2: " + q2.ToString() +
            "\nq3: " + q3.ToString() +
            "\nq4: " + q4.ToString() +
            "\ngripper: " + gripper.ToString();
        }
    }
}
