//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class MReengage : Message
    {
        public const string RosMessageName = "robotics_demo/Reengage";

        public int i;

        public MReengage()
        {
            this.i = 0;
        }

        public MReengage(int i)
        {
            this.i = i;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.i));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.i = BitConverter.ToInt32(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MReengage: " +
            "\ni: " + i.ToString();
        }
    }
}
