//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class MResetAngles : Message
    {
        public const string RosMessageName = "robotics_demo/ResetAngles";

        public float shoulder;
        public float upper_arm;
        public float forearm;
        public float wrist_1;
        public float wrist_2;
        public float wrist_3;
        public float outer_knuckle_left;
        public float inner_finger_left;
        public float inner_knuckle_left;
        public float outer_knuckle_right;
        public float inner_finger_right;
        public float inner_knuckle_right;

        public MResetAngles()
        {
            this.shoulder = 0.0f;
            this.upper_arm = 0.0f;
            this.forearm = 0.0f;
            this.wrist_1 = 0.0f;
            this.wrist_2 = 0.0f;
            this.wrist_3 = 0.0f;
            this.outer_knuckle_left = 0.0f;
            this.inner_finger_left = 0.0f;
            this.inner_knuckle_left = 0.0f;
            this.outer_knuckle_right = 0.0f;
            this.inner_finger_right = 0.0f;
            this.inner_knuckle_right = 0.0f;
        }

        public MResetAngles(float shoulder, float upper_arm, float forearm, float wrist_1, float wrist_2, float wrist_3, float outer_knuckle_left, float inner_finger_left, float inner_knuckle_left, float outer_knuckle_right, float inner_finger_right, float inner_knuckle_right)
        {
            this.shoulder = shoulder;
            this.upper_arm = upper_arm;
            this.forearm = forearm;
            this.wrist_1 = wrist_1;
            this.wrist_2 = wrist_2;
            this.wrist_3 = wrist_3;
            this.outer_knuckle_left = outer_knuckle_left;
            this.inner_finger_left = inner_finger_left;
            this.inner_knuckle_left = inner_knuckle_left;
            this.outer_knuckle_right = outer_knuckle_right;
            this.inner_finger_right = inner_finger_right;
            this.inner_knuckle_right = inner_knuckle_right;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.shoulder));
            listOfSerializations.Add(BitConverter.GetBytes(this.upper_arm));
            listOfSerializations.Add(BitConverter.GetBytes(this.forearm));
            listOfSerializations.Add(BitConverter.GetBytes(this.wrist_1));
            listOfSerializations.Add(BitConverter.GetBytes(this.wrist_2));
            listOfSerializations.Add(BitConverter.GetBytes(this.wrist_3));
            listOfSerializations.Add(BitConverter.GetBytes(this.outer_knuckle_left));
            listOfSerializations.Add(BitConverter.GetBytes(this.inner_finger_left));
            listOfSerializations.Add(BitConverter.GetBytes(this.inner_knuckle_left));
            listOfSerializations.Add(BitConverter.GetBytes(this.outer_knuckle_right));
            listOfSerializations.Add(BitConverter.GetBytes(this.inner_finger_right));
            listOfSerializations.Add(BitConverter.GetBytes(this.inner_knuckle_right));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.shoulder = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.upper_arm = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.forearm = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.wrist_1 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.wrist_2 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.wrist_3 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.outer_knuckle_left = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.inner_finger_left = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.inner_knuckle_left = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.outer_knuckle_right = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.inner_finger_right = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.inner_knuckle_right = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MResetAngles: " +
            "\nshoulder: " + shoulder.ToString() +
            "\nupper_arm: " + upper_arm.ToString() +
            "\nforearm: " + forearm.ToString() +
            "\nwrist_1: " + wrist_1.ToString() +
            "\nwrist_2: " + wrist_2.ToString() +
            "\nwrist_3: " + wrist_3.ToString() +
            "\nouter_knuckle_left: " + outer_knuckle_left.ToString() +
            "\ninner_finger_left: " + inner_finger_left.ToString() +
            "\ninner_knuckle_left: " + inner_knuckle_left.ToString() +
            "\nouter_knuckle_right: " + outer_knuckle_right.ToString() +
            "\ninner_finger_right: " + inner_finger_right.ToString() +
            "\ninner_knuckle_right: " + inner_knuckle_right.ToString();
        }
    }
}
