//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class MResetInfo : Message
    {
        public const string RosMessageName = "robotics_demo/ResetInfo";

        public MJointPositions joints;
        public MAchievedGoal ag;
        public MVelocities vels;

        public MResetInfo()
        {
            this.joints = new MJointPositions();
            this.ag = new MAchievedGoal();
            this.vels = new MVelocities();
        }

        public MResetInfo(MJointPositions joints, MAchievedGoal ag, MVelocities vels)
        {
            this.joints = joints;
            this.ag = ag;
            this.vels = vels;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(joints.SerializationStatements());
            listOfSerializations.AddRange(ag.SerializationStatements());
            listOfSerializations.AddRange(vels.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.joints.Deserialize(data, offset);
            offset = this.ag.Deserialize(data, offset);
            offset = this.vels.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MResetInfo: " +
            "\njoints: " + joints.ToString() +
            "\nag: " + ag.ToString() +
            "\nvels: " + vels.ToString();
        }
    }
}
