//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class MScalarRecording : Message
    {
        public const string RosMessageName = "robotics_demo/ScalarRecording";

        public float value;

        public MScalarRecording()
        {
            this.value = 0.0f;
        }

        public MScalarRecording(float value)
        {
            this.value = value;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.value));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.value = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MScalarRecording: " +
            "\nvalue: " + value.ToString();
        }
    }
}
