//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class MgetTimeResponse : Message
    {
        public const string RosMessageName = "robotics_demo/getTime";

        public double time_rec;

        public MgetTimeResponse()
        {
            this.time_rec = 0.0;
        }

        public MgetTimeResponse(double time_rec)
        {
            this.time_rec = time_rec;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.time_rec));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.time_rec = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MgetTimeResponse: " +
            "\ntime_rec: " + time_rec.ToString();
        }
    }
}
