//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class MgetTimeRequest : Message
    {
        public const string RosMessageName = "robotics_demo/getTime";

        public double time_sent;

        public MgetTimeRequest()
        {
            this.time_sent = 0.0;
        }

        public MgetTimeRequest(double time_sent)
        {
            this.time_sent = time_sent;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.time_sent));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.time_sent = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MgetTimeRequest: " +
            "\ntime_sent: " + time_sent.ToString();
        }
    }
}
