//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class MgetIKResponse : Message
    {
        public const string RosMessageName = "robotics_demo/getIK";

        public MJointPositions joints;

        public MgetIKResponse()
        {
            this.joints = new MJointPositions();
        }

        public MgetIKResponse(MJointPositions joints)
        {
            this.joints = joints;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(joints.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.joints.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MgetIKResponse: " +
            "\njoints: " + joints.ToString();
        }
    }
}
