//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class MgetIKRequest : Message
    {
        public const string RosMessageName = "robotics_demo/getIK";

        public MRPYProprioState RPYPos;
        public MJointPositions prev_joints;

        public MgetIKRequest()
        {
            this.RPYPos = new MRPYProprioState();
            this.prev_joints = new MJointPositions();
        }

        public MgetIKRequest(MRPYProprioState RPYPos, MJointPositions prev_joints)
        {
            this.RPYPos = RPYPos;
            this.prev_joints = prev_joints;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(RPYPos.SerializationStatements());
            listOfSerializations.AddRange(prev_joints.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.RPYPos.Deserialize(data, offset);
            offset = this.prev_joints.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MgetIKRequest: " +
            "\nRPYPos: " + RPYPos.ToString() +
            "\nprev_joints: " + prev_joints.ToString();
        }
    }
}
