//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class MresetRequest : Message
    {
        public const string RosMessageName = "robotics_demo/reset";

        public MResetAngles resetAngles;
        public MAchievedGoal ag;

        public MresetRequest()
        {
            this.resetAngles = new MResetAngles();
            this.ag = new MAchievedGoal();
        }

        public MresetRequest(MResetAngles resetAngles, MAchievedGoal ag)
        {
            this.resetAngles = resetAngles;
            this.ag = ag;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(resetAngles.SerializationStatements());
            listOfSerializations.AddRange(ag.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.resetAngles.Deserialize(data, offset);
            offset = this.ag.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MresetRequest: " +
            "\nresetAngles: " + resetAngles.ToString() +
            "\nag: " + ag.ToString();
        }
    }
}
